import { Roboto } from 'next/font/google'
import './globals.css'

import AppProvider from './Context/AppContext'

const RobotoBold = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${RobotoBold.className}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
