import { Roboto } from "next/font/google";
import {} from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from "./../components/SessionProvider";

const RobotoBold = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={RobotoBold.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
