import { Roboto } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/toaster"


import AppProvider from './Context/AppContext'
import AdminContext from './Context/adminContext'

const RobotoBold = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${RobotoBold.className}`}>
        <AppProvider>
          <AdminContext>
            {children}
          </AdminContext>
        </AppProvider>
        <Toaster />
      </body>
    </html>
  )
}
